# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
  - job: windows
    displayName: 'Build - Windows'
    continueOnError: false
    pool:
      vmImage: 'windows-latest'
    workspace:
      clean: all
    steps:
      - script: |
          MD build
      - script: |
          git clone https://github.com/oatpp/oatpp
          MD oatpp\build
        displayName: 'Checkout - oatpp'
        workingDirectory: build
      - script: |
          cmake ..
          cmake --build . --target INSTALL
        displayName: 'Build - oatpp'
        workingDirectory: build\oatpp\build
      - script: |
          cmake ..
          cmake --build .
        displayName: 'Build - module'
        workingDirectory: build
      - task: CopyFiles@2
        displayName: "Copy Headers oatpp"
        inputs:
          SourceFolder: "build/oatpp/src"
          Contents: "**/?(*.h|*.hpp)"
          TargetFolder: $(Build.ArtifactStagingDirectory)/includes
      - task: CopyFiles@2
        displayName: "Copy Library oatpp"
        inputs:
          SourceFolder: "build/oatpp/build/src/Debug"
          Contents: "oatpp.lib"
          TargetFolder: $(Build.ArtifactStagingDirectory)/lib/windows/
     
      - task: CopyFiles@2
        displayName: "Copy Headers oatpp-swagger"
        inputs:
          SourceFolder: "src/oatpp-swagger"
          Contents: "**/?(*.h|*.hpp)"
          TargetFolder: $(Build.ArtifactStagingDirectory)/includes/oatpp-swagger
      - task: CopyFiles@1
        displayName: "Copy Library oatpp-swagger"
        inputs:
          SourceFolder: "build/src/Debug"
          Contents: "oatpp-swagger.lib"
          TargetFolder: $(Build.ArtifactStagingDirectory)/lib/windows/
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifacts"
        inputs:
          pathToPublish: $(Build.ArtifactStagingDirectory)
          artifactName: Artifacts