# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
  - job: windows
    displayName: 'Build - Windows'
    continueOnError: false
    pool:
      vmImage: 'windows-latest'
    workspace:
      clean: all
    steps:
      - script: |
          MD build
      - script: |
          git clone https://github.com/oatpp/oatpp
          MD oatpp\build
        displayName: 'Checkout - oatpp'
        workingDirectory: build
      - task: CopyFiles@2
        displayName: "Copy Library"
        inputs:
          SourceFolder: "build/oatpp/build/src/Debug"
          Contents: "oatpp.lib"
          TargetFolder: $(Build.ArtifactStagingDirectory)/lib/windows/
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifacts"
        inputs:
          pathToPublish: $(Build.ArtifactStagingDirectory)
          artifactName: Artifacts
            
      - script: |
          cmake ..
          cmake --build . --target INSTALL
        displayName: 'Build - oatpp'
        workingDirectory: build\oatpp\build

      - script: |
          cmake ..
          cmake --build .
        displayName: 'Build - module'
        workingDirectory: build